### ISSUE TITLE
Podman: Container Fails to Start on First Run Due to Chown Reporting a "Permission Denied" Error

### ISSUE THREAD

**Issue by Saroufim** [crazy-max/docker-msmtpd#21]
#### Steps to reproduce this issue

1. Pull the container
2. Run it
3. Notice the failure

#### Expected behaviour
The container should start

#### Actual behaviour

Container fails on first run

### Configuration

* Docker version (type `docker --version`) : podman version 2.2.1
* Docker compose version if applicable (type `docker-compose --version`) : 
* Platform (Debian 9, Ubuntu 18.04, ...) :  Fedora 33
* System info (type `uname -a`) : Linux localhost.localdomain 5.9.13-200.fc33.armv7hl #1 SMP Tue Dec 8 16:34:16 UTC 2020 armv7l armv7l armv7l GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ... 
Container was created with podman run -d

### Docker info

```
host:
  arch: arm
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.armv7hl
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 01fe27cbb3699b1c48b58c068558f76868ff1198'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
```

### Logs
```

[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing... 
chown: /proc/self/fd/1: Permission denied
chown: /proc/self/fd/2: Permission denied
[cont-init.d] 00-fix-logs.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

**Comment by crazy-max** [comment]
@Saroufim This image is not intended to be working with Podman atm sorry. I suggest to [open an issue on Podman repo](https://github.com/containers/podman) about your issue and come back to me. Thanks.

**Comment by Saroufim** [comment]
If that is the issue then the container can be recreated using 'sudo podman'. Theoretically it should work as podman is almost fully compatible with docker. Of course, the issue would be whether the user is comfortable or not to run a mail server as a root container

**Comment by crazy-max** [comment]
@Saroufim I don't have a working podman service running but I will take a look when I've got some time.

**Comment by Saroufim** [comment]
I just tried to run it with sudo and it yielded the same errors. Perhaps there indeed is an incompatibility between docker and podman here.

**Comment by crazy-max** [comment]
@Saroufim 

> I just tried to run it with sudo and it yielded the same errors. Perhaps there indeed is an incompatibility between docker and podman here.

Yeah this part is quiet hacky to be able to stdout/stderr as a  standard user:

https://github.com/crazy-max/docker-msmtpd/blob/3800c486959746d24111dbbd88de6a25daaa1191/rootfs/etc/cont-init.d/00-fix-logs.sh#L4

I will find a proper way to handle this for both Docker/Podman.

**Comment by crazy-max** [comment]
@Saroufim I've installed podman on a fresh Debian and I cannot reproduce your issue:

```
$ podman run -t -p 2500:2500 --name msmtpd -e SMTP_HOST=smtp.example.com crazymax/msmtpd
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

I think you're getting this issue because SELinux is enforced. So you could just set SELinux to permissive in `/etc/sysconfig/selinux`.

Also this container changes its user internally from root to unprivileged so stdout/stderr is then inaccessible from the unprivileged user and that's why [`chown` is used](https://github.com/crazy-max/docker-msmtpd/blob/3800c486959746d24111dbbd88de6a25daaa1191/rootfs/etc/cont-init.d/00-fix-logs.sh#L4). (see also moby/moby#31243)

I've made a small change to not fail if we can't change ownership. Can you try with `crazymax/msmtpd:edge` image?

**Comment by Saroufim** [comment]
Hi, happy holidays!

It works perfectly now. Thanks a lot!
