### ISSUE TITLE
Different authentications

### ISSUE THREAD

**Issue by mmallejac** [crazy-max/docker-msmtpd#52]
Hello !

This is more a question than a bug report.

Our mail provider make it more and more difficult to accept mail relayed by our MSMTPD container when authentication user is not the same as the from address.
Is there a way to use MSMTPD so that authentication is different for each mail request ?

Thanks in advance

**Comment by crazy-max** [comment]
I'm not sure, I think you should ask at https://github.com/marlam/msmtp-mirror/issues

**Comment by mmallejac** [comment]
Thanks !
